<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE TS>
<TS version="1.1" language="zh_CN">
    <context>
        <name>QObject</name>
        <message>
            <source>TBR_ROTATION</source>
            <translation>动态旋转</translation>
        </message>
        <message>
            <source>MNU_GLOBALPAN</source>
            <translation>全局平移(&amp;G)</translation>
        </message>
        <message>
            <source>MNU_ROTATION</source>
            <translation>动态旋转(&amp;R)</translation>
        </message>
        <message>
            <source>MNU_AXO</source>
            <translation>轴测(&amp;A)</translation>
        </message>
        <message>
            <source>MNU_NEW</source>
            <translation>新建(&amp;N)</translation>
        </message>
        <message>
            <source>MNU_PAN</source>
            <translation>动态平移(&amp;P)</translation>
        </message>
        <message>
            <source>MNU_TOP</source>
            <translation>上视(&amp;T)</translation>
        </message>
        <message>
            <source>MNU_TOOL_SHAD</source>
            <translation>着色(&amp;S)</translation>
        </message>
        <message>
            <source>MNU_TOOL_WIRE</source>
            <translation>线框(&amp;W)</translation>
        </message>
        <message>
            <source>TBR_BOTTOM</source>
            <translation>下视</translation>
        </message>
        <message>
            <source>MNU_BOTTOM</source>
            <translation>下视(&amp;B)</translation>
        </message>
        <message>
            <source>BTN_BRONZE</source>
            <translation>青铜</translation>
        </message>
        <message>
            <source>MNU_BRONZE</source>
            <translation>青铜(&amp;B)</translation>
        </message>
        <message>
            <source>TBR_BRONZE</source>
            <translation>青铜</translation>
        </message>
        <message>
            <source>BTN_COPPER</source>
            <translation>铜</translation>
        </message>
        <message>
            <source>MNU_COPPER</source>
            <translation>铜(&amp;C)</translation>
        </message>
        <message>
            <source>TBR_COPPER</source>
            <translation>铜</translation>
        </message>
        <message>
            <source>MNU_TOOL_COLOR</source>
            <translation>颜色(&amp;C)</translation>
        </message>
        <message>
            <source>MNU_TOOL_MATER</source>
            <translation>材质(&amp;M)</translation>
        </message>
        <message>
            <source>TBR_FITALL</source>
            <translation>适配全部</translation>
        </message>
        <message>
            <source>MNU_FITALL</source>
            <translation>适配全部(&amp;F)</translation>
        </message>
        <message>
            <source>MNU_BACK</source>
            <translation>后视(&amp;B)</translation>
        </message>
        <message>
            <source>MNU_FILE</source>
            <translation>文件(&amp;F)</translation>
        </message>
        <message>
            <source>MNU_PREFERENCES</source>
            <translation>首选项(&amp;P)</translation>
        </message>
        <message>
            <source>MNU_USE_VBO</source>
            <translation>使用 VBO(&amp;V)</translation>
        </message>
        <message>
            <source>MNU_GOLD</source>
            <translation>金(&amp;G)</translation>
        </message>
        <message>
            <source>MNU_HELP</source>
            <translation>帮助(&amp;H)</translation>
        </message>
        <message>
            <source>MNU_LEFT</source>
            <translation>左视(&amp;L)</translation>
        </message>
        <message>
            <source>MNU_QUIT</source>
            <translation>退出(&amp;Q)</translation>
        </message>
        <message>
            <source>MNU_VIEW</source>
            <translation>视图(&amp;V)</translation>
        </message>
        <message>
            <source>MNU_ZOOM</source>
            <translation>动态缩放(&amp;Z)</translation>
        </message>
        <message>
            <source>MNU_HLROFF</source>
            <translation>隐藏线关闭(&amp;O)</translation>
        </message>
        <message>
            <source>TBR_HLROFF</source>
            <translation>隐藏线关闭</translation>
        </message>
        <message>
            <source>MNU_TOOL_TRANS</source>
            <translation>透明度(&amp;T)</translation>
        </message>
        <message>
            <source>MNU_TOOL_SHADOWS</source>
            <translation>阴影(&amp;S)</translation>
        </message>
        <message>
            <source>MNU_TOOL_RAYTRACING</source>
            <translation>光线追踪(&amp;R)</translation>
        </message>
        <message>
            <source>MNU_TOOL_REFLECTIONS</source>
            <translation>反射(&amp;R)</translation>
        </message>
        <message>
            <source>MNU_TOOL_ANTIALIASING</source>
            <translation>抗锯齿(&amp;A)</translation>
        </message>
        <message>
            <source>BTN_BRASS</source>
            <translation>黄铜</translation>
        </message>
        <message>
            <source>BTN_PEWTER</source>
            <translation>白镴</translation>
        </message>
        <message>
            <source>TBR_PEWTER</source>
            <translation>白镴</translation>
        </message>
        <message>
            <source>MNU_PEWTER</source>
            <translation>白镴(&amp;P)</translation>
        </message>
        <message>
            <source>MNU_SILVER</source>
            <translation>银(&amp;S)</translation>
        </message>
        <message>
            <source>BTN_OK</source>
            <translation>确定</translation>
        </message>
        <message>
            <source>TBR_SILVER</source>
            <translation>银</translation>
        </message>
        <message>
            <source>BTN_SILVER</source>
            <translation>银</translation>
        </message>
        <message>
            <source>INF_NULL_SHAPE</source>
            <translation>请选择要导出的形体。</translation>
        </message>
        <message>
            <source>MNU_WINDOW</source>
            <translation>窗口(&amp;W)</translation>
        </message>
        <message>
            <source>TBR_WINDOW</source>
            <translation>窗口</translation>
        </message>
        <message>
            <source>BTN_PLASTIC</source>
            <translation>塑料</translation>
        </message>
        <message>
            <source>BTN_PLASTER</source>
            <translation>石膏</translation>
        </message>
        <message>
            <source>MNU_PLASTIC</source>
            <translation>塑料(&amp;P)</translation>
        </message>
        <message>
            <source>MNU_PLASTER</source>
            <translation>石膏(&amp;P)</translation>
        </message>
        <message>
            <source>TBR_PLASTIC</source>
            <translation>塑料</translation>
        </message>
        <message>
            <source>TBR_PLASTER</source>
            <translation>石膏</translation>
        </message>
        <message>
            <source>MNU_TOOL_BAR</source>
            <translation>工具栏(&amp;T)</translation>
        </message>
        <message>
            <source>MNU_TOOL_DEL</source>
            <translation>删除(&amp;D)</translation>
        </message>
        <message>
            <source>TBR_BACK</source>
            <translation>后视</translation>
        </message>
        <message>
            <source>TBR_GOLD</source>
            <translation>金</translation>
        </message>
        <message>
            <source>TBR_LEFT</source>
            <translation>左视</translation>
        </message>
        <message>
            <source>TBR_QUIT</source>
            <translation>退出</translation>
        </message>
        <message>
            <source>TBR_VIEW</source>
            <translation>视图</translation>
        </message>
        <message>
            <source>TBR_ZOOM</source>
            <translation>动态缩放</translation>
        </message>
        <message>
            <source>MNU_CH_BACK</source>
            <translation>更改背景(&amp;B)</translation>
        </message>
        <message>
            <source>MNU_CH_ENV_MAP</source>
            <translation>环境贴图(&amp;E)</translation>
        </message>
        <message>
            <source>TBR_CH_BACK</source>
            <translation>更改背景</translation>
        </message>
        <message>
            <source>TBR_TOOL_COLOR</source>
            <translation>颜色</translation>
        </message>
        <message>
            <source>TBR_TOOL_MATER</source>
            <translation>材质</translation>
        </message>
        <message>
            <source>TBR_TOOL_RAYTRACING</source>
            <translation>启用光线追踪</translation>
        </message>
        <message>
            <source>TBR_TOOL_SHADOWS</source>
            <translation>启用阴影</translation>
        </message>
        <message>
            <source>TBR_TOOL_REFLECTIONS</source>
            <translation>启用反射</translation>
        </message>
        <message>
            <source>TBR_TOOL_ANTIALIASING</source>
            <translation>启用抗锯齿</translation>
        </message>
        <message>
            <source>TBR_TOOL_BAR</source>
            <translation>工具栏</translation>
        </message>
        <message>
            <source>TBR_TOOL_DEL</source>
            <translation>删除</translation>
        </message>
        <message>
            <source>TBR_TOOL_TRANS</source>
            <translation>透明度</translation>
        </message>
        <message>
            <source>TBR_ABOUT</source>
            <translation>关于</translation>
        </message>
        <message>
            <source>TBR_BRASS</source>
            <translation>黄铜</translation>
        </message>
        <message>
            <source>TBR_CLOSE</source>
            <translation>关闭</translation>
        </message>
        <message>
            <source>TBR_FRONT</source>
            <translation>前视</translation>
        </message>
        <message>
            <source>TBR_HLRON</source>
            <translation>隐藏线显示</translation>
        </message>
        <message>
            <source>TBR_MATER</source>
            <translation>材质</translation>
        </message>
        <message>
            <source>TBR_RIGHT</source>
            <translation>右视</translation>
        </message>
        <message>
            <source>TBR_RESET</source>
            <translation>重置</translation>
        </message>
        <message>
            <source>TBR_AXO</source>
            <translation>轴测</translation>
        </message>
        <message>
            <source>TBR_NEW</source>
            <translation>新建</translation>
        </message>
        <message>
            <source>TBR_PAN</source>
            <translation>动态平移</translation>
        </message>
        <message>
            <source>TBR_TOP</source>
            <translation>上视</translation>
        </message>
        <message>
            <source>TIT_INF</source>
            <translation>信息</translation>
        </message>
        <message>
            <source>BTN_GOLD</source>
            <translation>金</translation>
        </message>
        <message>
            <source>TBR_WINDOW_NEW3D</source>
            <translation>新建 3D 视图</translation>
        </message>
        <message>
            <source>MNU_WINDOW_NEW3D</source>
            <translation>新建 3D 视图</translation>
        </message>
        <message>
            <source>MNU_STATUS_BAR</source>
            <translation>状态栏(&amp;S)</translation>
        </message>
        <message>
            <source>TIT_ERROR</source>
            <translation>错误</translation>
        </message>
        <message>
            <source>TBR_FITAREA</source>
            <translation>窗口缩放</translation>
        </message>
        <message>
            <source>MNU_FITAREA</source>
            <translation>窗口缩放(&amp;Z)</translation>
        </message>
        <message>
            <source>TBR_GLOBALPAN</source>
            <translation>全局平移</translation>
        </message>
        <message>
            <source>MNU_ABOUT</source>
            <translation>关于(&amp;A)</translation>
        </message>
        <message>
            <source>MNU_BRASS</source>
            <translation>黄铜(&amp;B)</translation>
        </message>
        <message>
            <source>MNU_CLOSE</source>
            <translation>关闭(&amp;C)</translation>
        </message>
        <message>
            <source>MNU_FRONT</source>
            <translation>前视(&amp;F)</translation>
        </message>
        <message>
            <source>MNU_HLRON</source>
            <translation>隐藏线显示(&amp;H)</translation>
        </message>
        <message>
            <source>MNU_MATER</source>
            <translation>材质(&amp;M)</translation>
        </message>
        <message>
            <source>MNU_RIGHT</source>
            <translation>右视(&amp;R)</translation>
        </message>
        <message>
            <source>MNU_RESET</source>
            <translation>重置(&amp;R)</translation>
        </message>
        <message>
            <source>INF_ABOUT</source>
            <translation>基于 Qt 的 Open CASCADE Technology 教学示例程序</translation>
        </message>
        <message>
            <source>INF_READY</source>
            <translation>就绪</translation>
        </message>
        <message>
            <source>TBR_TOOL_SHAD</source>
            <translation>着色</translation>
        </message>
        <message>
            <source>TBR_TOOL_WIRE</source>
            <translation>线框</translation>
        </message>
        <message>
            <source>TBR_WINDOW_TILE</source>
            <translation>平铺</translation>
        </message>
        <message>
            <source>TBR_STATUS_BAR</source>
            <translation>状态栏</translation>
        </message>
        <message>
            <source>MNU_WINDOW_CASCADE</source>
            <translation>层叠</translation>
        </message>
        <message>
            <source>TBR_WINDOW_CASCADE</source>
            <translation>层叠</translation>
        </message>
        <message>
            <source>MNU_WINDOW_TILE</source>
            <translation>平铺(&amp;T)</translation>
        </message>
    </context>
    <context>
        <name>ApplicationCommonWindow</name>
        <message>
            <source>File Operations</source>
            <translation>文件操作</translation>
        </message>
        <message>
            <source>View Operations</source>
            <translation>视图操作</translation>
        </message>
        <message>
            <source>Shape Operations</source>
            <translation>形体显示</translation>
        </message>
        <message>
            <source>Ray-tracing Options</source>
            <translation>光线追踪选项</translation>
        </message>
    </context>
    <context>
        <name>DLMUI_FileWnd</name>
        <message>
            <source>File Operations</source>
            <translation>文件操作</translation>
        </message>
    </context>
    <context>
        <name>DLMUI_ViewOps</name>
        <message>
            <source>View Operations</source>
            <translation>视图操作</translation>
        </message>
    </context>
    <context>
        <name>DLMUI_ModelSkin</name>
        <message>
            <source>Shape Operations</source>
            <translation>形体显示</translation>
        </message>
    </context>
    <context>
        <name>DLMUI_Raytrace</name>
        <message>
            <source>Ray-tracing Options</source>
            <translation>光线追踪选项</translation>
        </message>
    </context>
    <context>
        <name>DLMUI_BackgroundSet</name>
        <message>
            <source>Open File</source>
            <translation>打开文件</translation>
        </message>
        <message>
            <source>All Image Files (*.bmp *.gif *.jpg *.jpeg *.png *.tga)</source>
            <translation>所有图像文件 (*.bmp *.gif *.jpg *.jpeg *.png *.tga)</translation>
        </message>
    </context>
</TS>